# Dockerfile has been added in all micro-services, you need to dockerize all micro-services and add docker-compose.yml file
version: '3'
services:
  user-mysql:
    image: mysql:5.7
    network_mode: host
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: userDb
      MYSQL_HOST: localhost

  db-mongo:
    image: mongo
    network_mode: host
    ports:
      - "27017:27017"
    environment:
      MONGO_DATABASE: KeepNoteDB
      MONGO_PORT: 27017
      MONGO_HOST: localhost
  
  user-auth-service:
    image: user-auth-service
    build:
      context: UserAuthentication-Service/
    depends_on:
      - user-mysql
    ports:
      - "8089:8089"
    network_mode: host
    restart: always

  user-service:
    build:
      context: UserService/
    depends_on:
      - db-mongo
    ports:
      - "8082:8082"
    network_mode: host
    restart: always
    
  note-service:
    build:
      context: NoteService/
    depends_on:
      - db-mongo
    ports:
      - "8083:8083"
    network_mode: host
    restart: always



