spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/AuthenticationServiceDB?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: v3ry$3cur3PASSWORD
  jpa:
    hibernate:      ddl-auto: create
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8089
