FROM java:11-jre
COPY ./target/UserAuthentication-Service-0.0.1-SNAPSHOT.jar /usr/src/UserAuthentication-Service-0.0.1-SNAPSHOT.jar
WORKDIR /usr/src
CMD ["java","-jar","/usr/src/UserAuthentication-Service-0.0.1-SNAPSHOT.jar"]